### ISSUE TITLE
Support TCP

### ISSUE THREAD

**Issue by wvengen** [klingtnet/rosc#19]
When working with TCP, the [OSC spec](http://cnmat.org/OpenSoundControl/OSC-spec.html) mentions:
> In a stream-based protocol such as TCP, the stream should begin with an int32 giving the size of the first packet, followed by the contents of the first packet, followed by the size of the second packet, etc.

I've had much trouble with rosc to use TCP, reading this little line in the spec I finally understand. Is it true that rosc doesn't implement this right now, and if so, would this be a good idea to have?

**Comment by klingtnet** [comment]
Given the signature of [`decode`](https://github.com/klingtnet/rosc/blob/55edf66ac678a7a0cde315c21ec28df4ea5c8623/src/decoder.rs#L18) and [encode](https://github.com/klingtnet/rosc/blob/55edf66ac678a7a0cde315c21ec28df4ea5c8623/src/encoder.rs#L23) `rosc` is actually transport agnostic since it consumes and produces slices of bytes. I guess the spec proposes to send the size of each packet when using TCP in case you want to send more than one OSC package/message in one TCP connection.  It would likely be beneficial if `rosc` would provide some higher level networking abstractions but I lost track of how one is now doing proper networking with Rust when the whole asyncio thing happenend.

**Comment by wvengen** [comment]
Thanks for your response!
I understand you've left out the networking part from `rosc`, I think that's fine. Someone else could provide a crate integrating `rosc` with a certain approach to networking. The existing examples here are helpful already for people wanting to use this.

Perhaps something like `fn decode_tcp(msgs: &[u8]) -> Result<Vec<OscPacket>>` and `fn encode_tcp(packets: &Vec<OscPacket>) -> Result<Vec<u8>>` would still be useful. (Though I'm not sure if it should be `&Vec<OscPacket>` or `Vec<&OscPacket>`.)

**Comment by klingtnet** [comment]
> Perhaps something like fn decode_tcp(msgs: &[u8]) -> Result<Vec<OscPacket>> and fn encode_tcp(packets: &Vec<OscPacket>) -> Result<Vec<u8>> would still be useful. (Though I'm not sure if it should be &Vec<OscPacket> or Vec<&OscPacket>.)

Yes, this would be helpful when interacting with other OSC implementations over TCP which follow the spec closely.  Would you mind to contribute an implementation of those two functions?  I can implement this as well but cannot guarantee when I will find the time to do that.

**Comment by klingtnet** [comment]
This got finally resolved with #21 , but there is no release yet.  A proper release will follow  as soon as we removed the dependency on the regex crate.
